#!/usr/bin/env bash

set -euo pipefail

SCRIPT_PATH="$(realpath "$(dirname "$(realpath "$0")")")"

echo "Updating flake inputs..."
nix flake update --accept-flake-config --flake "$SCRIPT_PATH"
echo "Rebuilding..."
"$SCRIPT_PATH/rebuild" -s -u "$@"
