# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0dd71a22-dd1d-49fa-b929-5106f43ca492";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0dd71a22-dd1d-49fa-b929-5106f43ca492".device = "/dev/disk/by-uuid/0dd71a22-dd1d-49fa-b929-5106f43ca492";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C57D-6223";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7e97feac-3032-44b6-8d01-233e4392164e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
